# Generated by Django 2.2.5 on 2019-11-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_auto_20191118_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
